# Bật tính năng ZMK Studio
CONFIG_ZMK_STUDIO=y

# Kích hoạt lưu cấu hình vào bộ nhớ flash (để phím nhớ keymap sau khi đổi)
CONFIG_ZMK_SETTINGS_SAVE_ON_CHANGE=y

# Các cấu hình cũ của bạn
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_USB_LOGGING=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
